PTE_Forms/PTE_Forms/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name = "home"),
    path('accounts/',include('accounts.urls'), name='accounts'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('pteforms/',include('pteforms.urls'), name='pteforms'),
    path('lots/',include('lots.urls'), name='lots'),
    path('test/',views.TestPage.as_view(), name = 'test'),
    path('thanks/',views.ThanksPage.as_view(), name = 'thanks'),
]

PTE_Forms/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('signup/',views.SignUp.as_view(), name='signup'),
]

PTE_Forms/lots/urls.py
from django.urls import path
from . import views

app_name = 'lots'

urlpatterns = [
    path('',views.ListLot.as_view(), name='all'),
    path('new/',views.CreateLot.as_view(), name='create'),
    path('<slug:slug>/',views.SingleLot.as_view(),name='single'),
]

PTE_Forms/pteforms/urls.py
from django.urls import path, include
from . import views


app_name = 'pteforms'

urlpatterns = [
    path('',views.GramStainList.as_view(), name='all'),
    path('newgramstain/',views.CreateGramStain.as_view(), name='create'),
    path('lot/<lot_number>/>',views.LotGramStain.as_view(), name='for_lot'),
    path('lot/<lot_number>/<int:pk>',views.GramStainDetail.as_view(), name='single'),
    path('delete/<int:pk>',views.DeleteGramStain.as_view(), name='delete'),

]

PTE_Forms/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

PTE_Forms/lots/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
User = get_user_model()
from django import template
register = template.Library()
from django.urls import reverse
# Create your models here.

class Lot(models.Model):
    lot_number = models.CharField(max_length=10, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    harvest_size = models.DecimalField(max_digits=6, decimal_places=2)
    date_shipped = models.DateField()
    date_received = models.DateField()

    def __str__(self):
        return self.lot_number

    def save(self,*args,**kwargs):
        self.slug = slugify(self.lot_number)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('lots:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['lot_number']


    pass

PTE_Forms/pteforms/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from lots.models import Lot
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

class GramStain(models.Model):
    lot_number = models.ForeignKey(Lot, related_name="gramstainform", on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    completion_time = models.DateTimeField()
    email = models.EmailField()
    name = models.CharField(max_length=256)
    technician_name = models.CharField(max_length=256)
    colony_count = models.PositiveIntegerField()
    organism_discription = models.TextField(max_length=256)
    gram_stain_result = models.BooleanField()

    def __str__(self):
        return self.lot_number

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse("pteforms:single",kwargs={'pk':self.pk})

    class Meta:
        ordering = ['-start_time']

PTE_Forms/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Name'
        self.fields['email'].label = "Email Address"

PTE_Forms/pteforms/forms.py
from django import forms
from pteforms.models import GramStain

class GramStainForm(forms.ModelForm):
    class Meta():
        model = GramStain
        fields = "__all__"

PTE_Forms/PTE_Forms/views.py
from django.views import generic
from django.shortcuts import render

class HomePage(generic.TemplateView):
    template_name = 'index.html'

class TestPage(generic.TemplateView):
    template_name = 'test.html'

class ThanksPage(generic.TemplateView):
    template_name = 'thanks.html'

PTE_Forms/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from . import forms


# Create your views here.
class SignUp(generic.CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

PTE_Forms/lots/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from lots.models import Lot

# Create your views here.
class CreateLot(LoginRequiredMixin, generic.CreateView):
    fields = ('lot_number','harvest_size','date_shipped','date_received')
    model = Lot

class SingleLot(generic.DetailView):
    model = Lot

class ListLot(generic.ListView):
    model = Lot 

PTE_Forms/pteforms/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404
from . import models
from . import forms
from braces.views import SelectRelatedMixin
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

class GramStainList(SelectRelatedMixin, generic.ListView):
     model = models.GramStain
     select_related = ('lot')

class LotGramStain(generic.ListView):
    model = models.GramStain
    template_name = 'pteforms/pteforms_list.html'

    def get_queryset(self):
        try:
            return self.gramstain.all()
        except GramStain.DoesNotExist:
            raise Http404
        else:
            return self.gramstain.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['lot_number'] = self.lot_number
        return context

class GramStainDetail(SelectRelatedMixin, generic.DetailView):
    model = models.GramStain
    select_related = ('lot_number')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(lot__lot_number__iexact=self.kwargs.get('lot_number'))

class CreateGramStain(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('__all__')
    model = models.GramStain
    success_url = reverse_lazy ('lots:all')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeleteGramStain(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.GramStain
    select_related = ('lot_number')
    success_url = reverse_lazy ('lots:all')

    def get_queryset(self):
        queryset = super().get.queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request, 'Gram Stain Deleted')
        return super().delete(*args,**kwargs)

PTE_Forms/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div id="form" class="container">
  <h1>Login</h1>
  <form  method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input id='submit' type="submit" class='btn btn-primary' value="Login">
  </form>

</div>
{% endblock%}

PTE_Forms/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div id="form" class="container ">
  <h1 id='title'>Sign Up</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
  </form>
  <input id='submit' type="submit" class='btn btn-primary' value="Sign Up">
</div>



{% endblock%}

PTE_Forms/lots/templates/lots/lot_detail.html
{% extends 'lots/lots_base.html' %}
{% block prelot %}

<h1>{{lot.lot_number}}</h1>



{% endblock %}

(% block lot_content %)
<div class="col-md-8">
  {% if lot.gramstain.count ==0 %}
    <h2>No GramStain From has been filled out</h2>
  {% else %}
    {% for pteform in lot.gramstain.all %}
      {% include "pteforms/_pteforms.html" %}
  {% endfor %}
  {% endif %}
</div>


{% endblock %}

PTE_Forms/lots/templates/lots/lot_form.html
{% extends 'lots/lots_base.html' %}
{% load bootstrap5 %}

{% block lot_content %}
<h4>Create a new Lot</h4>

<form  action="{% url 'lots:create'%}" method="post" id='lotForm'>
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary btn-large" value="Create">
</form>
{% endblock %}

PTE_Forms/lots/templates/lots/lot_list.html
{% extends 'lots/lots_base.html' %}

{% block prelot %}

<div class="col-md-4">
  <div class="content">
    {% if user.is_authenicated %}
    <h2>Welcome Back!
      <a href="{% url 'pteforms:for_user' username=user.username %}">
        @{{user.username}}
      </a>
    </h2>
    {% endif %}
    <h2>Lots</h2>
    <p>Current Lots in the pipeline </p>
  </div>


  {% if user.is_authenicated %}
    <a href="{% url 'lots:all' %}" class='btn btn-md btn-fill btn-warning'>
    <span class='glyphicon glyphicon-plus-sign'>Create New Lot</span></a>
  {% endif %}
</div>
<div class="d-grid gap2 d-md-flex justify-content-md-end">
  <a href="{% url 'lots:create' %}" class='btn btn-md btn-fill btn-primary'>Create New Lot</a>
</div>

{% endblock %}

{% block lot_content %}

<table class = 'table table-striped'>
  <thead>
    <tr>
      <th>Lot Number</th>
      <th>Harvest Size</th>
      <th>Date Shipped</th>
      <th>Date Received</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for object in object_list %}
          <td><a href="#">{{object.lot_number}}</a></td>
          <td>{{object.harvest_size}}</td>
          <td>{{object.date_shipped}}</td>
          <td>{{object.date_received}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


<!-- <div class=
</table>
  <tbody>
    <tr>
      <td><a href="#">{{lot.lot_number}}</a></td>
      <td>{{lot.harvest_size}}</td>
      <td>{{lot.date_shipped}}</td>
      <td>{{lot.date_received}}</td>
    </tr>
  </tbody>
<!-- <div class="col-md-">
  <div class="list-lots"> -->
    <!-- {% for lot in object_list %} -->
      <!-- <a class='list-lot-item' href="{% url 'lots:single' slug=lot.slug %}">
        <table class='table'>{{lot.lot_number}}</table>
        <div class="list-lot-item-text container-fluid">
          <div class="row">
            <div class="col-md-4">
            </div>
          </div>
        </div>
      </a> -->
      <!-- <table class="table"> -->

    <!-- {% endfor %}
  </div>
</div> -->
{% endblock %}

PTE_Forms/lots/templates/lots/lots_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    {% block prelot %}{% endblock %}
    {% block lot_content %}{% endblock %}
    {% block postlot %}{% endblock %}
  </div>
</div>
{% endblock %}

PTE_Forms/pteforms/templates/pteforms/gramstain_form.html
{% extends 'pteforms/pteforms_base.html' %}
{% load bootstrap5 %}
{% block form_content %}
<div class="container">
  <h1>Gram Stain Form</h1>
    <form  action="{% url 'lots:create' %}" method="post" id='lotform'>
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary btn-large" value="Create">
    </form>
</div>

{% endblock %}

PTE_Forms/pteforms/templates/pteforms/pteforms_base.html
{% extends 'base.html' %}
{% block content %}
<div class="forms-page">
  {% block preform %}{% endblock %}
  {% block form_content %}{% endblock %}
  {% block postform %}{% endblock %}
</div>

{% endblock %}

PTE_Forms/pteforms/templates/pteforms/pteforms_list.html
{% extends 'pteforms/pteforms_base.html' %}

{% block preform %}

<div class="col-md-4">
  
</div>
{% endblock %}

PTE_Forms/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>PTE Forms</title>
    <!-- MASTER CSS -->
    <link rel="stylesheet" href="{% static 'PTE_Forms/css/master.css'%}">
    <!-- BOOTSTRAP 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
    <a class='navbar-brand' href="{% url 'home' %}"><img src="https://marketexclusive.com/wp-content/uploads/2017/02/PolarityTE-Logo.png" height='50'></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if user.is_authenticated %}
          <a class="nav-link active" aria-current="page" href="{% url 'lots:all' %}">Lots</a>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Forms
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Gram Stain</a></li>
              <li><a class="dropdown-item" href="#">Processing Room</a></li>
              <li><a class="dropdown-item" href="#">Harvest Skin Quality Score</a></li>
            </ul>
          </li>
          <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
        {% else %}
            <a class="nav-link active" aria-current="page" href="{% url 'lots:all' %}">Lots</a>
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">Sign Up</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>
    <div class="container mycontent">
      {% block content %}
      {% endblock %}
    </div>

  </body>
  <script type="text/javascript" src="{% static 'PTE_Forms/js/master.js' %}">

  </script>
</html>

PTE_Forms/templates/index.html
{% extends  'base.html' %}
{% block content %}
<div class="container">
  <!-- <ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="#">Gram Stain</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled">Disabled</a>
  </li>
</ul> -->
<h1>Welcome to PTE Forms</h1>
</div>
{% endblock %}

PTE_Forms/templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>You are now logged in</h1>
{% endblock %}

PTE_Forms/templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for logging out!</h1>
{% endblock %}